# Weclome to chat links created by Joshter1!

# Reload color configuration
reload: "&a&lReloaded Links"

# How to configure:
# Make sure each 'message type' has the same number of lines. You may add empty strings by adding ""

# What will be displayed in chat before the clickable link
prefix_messages:
  - "&3========  &e&lServer Links  &3========"
  - ""
  - "&b&lWebsite &7 "
  - "&b&lYoutube &7 "
  - "&b&lDiscord &7 "
  - ""
  - "&3================================"
  

# What will be displayed in chat after the clickable link
suffix_messages:
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  

# What the clickable link will be displayed as in chat
linked_message:
  - ""
  - ""
  - "&3&lClick Here"
  - "&3&lClick Here"
  - "&3&lClick Here"
  - ""
  - ""
  

# What message will be displayed when hovering over the link
hover:
  - ""
  - ""
  - "&3Click Here to Visit our Website"
  - "&3Click Here to Visit our Youtube"
  - "&3Click Here to Visit our Discord"
  - ""
  - ""
  
# What website will you be redirected to when clicked on
# Make sure you type in the entire link or the plugin will not load properly
links:
  - ""
  - ""
  - "http://Example.com"
  - "http://Youtube.com"
  - "http://Discord.com"
  - ""
  - ""
